name: release-please

on:
  push:
    branches:
      - main

# Required permissions for release-please to open PRs and create releases
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          # token defaults to GITHUB_TOKEN; add a PAT secret if you need
          # other workflows to trigger from Release Please PRs/releases.
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
